# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'StripeTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '5.6.0'
  pod 'Stripe', '23.2.0'
  pod 'Alamofire', '5.6.1'
  pod 'SVProgressHUD', '2.2.5'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end

end
