# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StripeTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Stripe', '5.0.1'
  pod 'SnapKit', '21.7.0'

end
